# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://the-internet.herokuapp.com/")
    self.driver.set_window_size(1361, 907)
    self.driver.find_element(By.LINK_TEXT, "Form Authentication").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("tomsmith")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".subheader").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("SuperSecretPassword!")
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    self.driver.find_element(By.ID, "flash").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".icon-2x")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".icon-2x").text == "Logout"
    assert self.driver.find_element(By.ID, "flash").text == "You logged into a secure area!\n×"
    self.driver.find_element(By.CSS_SELECTOR, ".icon-2x").click()
    self.driver.find_element(By.ID, "page-footer").click()
    assert self.driver.find_element(By.ID, "flash").text == "You logged out of the secure area!\n×"
    assert self.driver.title == "The Internet"
    self.vars["current_url"] = self.driver.execute_script("return window.location.href")
    assert(self.vars["current_url"] == "https://the-internet.herokuapp.com/login")
  
